export const companyMockData = [
	{
		"companyID": 1,
		"companyName": "Tricon",
		"companyClass": 4,
		"companyDescription": "We are an IT Consulting and Software Services Company headquartered in Bangalore, India with offices in the USA, Australia and the Middle East. We help businesses deliver consistent, compelling, innovative, and agile digital experiences. We are continuously innovating to provide best in class IT consulting, software development services, design services, custom products, mobility, and cloud operations. Our solutions have empowered businesses across industry verticals and geographies to make the right decisions while focusing on their core business",
		"companyEstablishment": "1997",
		"companyWebsite": "https://www.triconinfotech.com/",
		"companyAddDate": "2022-12-18T23:33:29.000Z",
		"companyAddedBy": 7,
		"ImageID": "1Gjc-4L98OWAMi67ZxkVZQFJuvasj1SMf",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 2,
		"companyName": "HCL",
		"companyClass": null,
		"companyDescription": "Established in 1976 as one of India’s original IT garage start-ups, HCL is a pioneer of modern computing with many firsts to its credit, including the introduction of the 8-bit microprocessor-based computer in 1978 well before its global peers. Today, the HCL enterprise has a presence across varied sectors that include technology, healthcare, and talent management solutions and comprises three companies – HCL Infosystems, HCL Technologies, and HCL Healthcare. The enterprise generates annual revenues of over US $11.2 Billion global technology firm with over 198,000 professionals operating from 52 countries.",
		"companyEstablishment": "1976",
		"companyWebsite": "https://hcl.com/",
		"companyAddDate": "2024-01-01T05:28:11.000Z",
		"companyAddedBy": null,
		"ImageID": null,
		"classID": null,
		"className": null,
		"userID": null,
		"userName": null,
		"userEmail": null,
		"userPassword": null,
		"userType": null
	},
	{
		"companyID": 3,
		"companyName": "Xceedence",
		"companyClass": 4,
		"companyDescription": "Xceedance is a global provider of strategic operations support (SOS), which includes consulting, managed services, data sciences, and technology across the entire insurance lifecycle. Insurance organizations can achieve their target operating models with the help and experience of Xceedance . The company’s proficiency extends to underwriting, actuarial services, catastrophe modeling and exposure management, policy services, claims, BI and reporting, finance and accounting, and application development.",
		"companyEstablishment": "2013",
		"companyWebsite": "https://xceedance.com/",
		"companyAddDate": "2022-12-18T23:34:54.000Z",
		"companyAddedBy": 7,
		"ImageID": "1ThJ8vuuysy3Pczo1IciAxleVvlWk1CiG",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 4,
		"companyName": "MG MOTORS",
		"companyClass": 2,
		"companyDescription": "MG Motor India Private Limited is an automobile Manufacturer in India, a subsidiary of Chinese automotive manufacturer SAIC Motor which marketed Vehicles under the British MG marque. It was setup in the year 2017 and began its sales and manufacturing operations in 2019.",
		"companyEstablishment": "2017",
		"companyWebsite": "https://www.mgmotor.co.in/",
		"companyAddDate": "2022-12-18T23:36:08.000Z",
		"companyAddedBy": 7,
		"ImageID": "1nurnWMmdhAFrNKnEcVp683j75n6X2l8i",
		"classID": 2,
		"className": "Core",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 5,
		"companyName": "Accenture",
		"companyClass": 1,
		"companyDescription": "Accenture PLC is an Irish-based multinational professional services company that specializes in IT services and consulting. A Fortune Global 500 company, it reported revenues of $44.33 billion in 2020 and had 569,000 employees. In 2015, the company had about 150,000 employees in India, 48,000 in the US, and 50,000 in the Philippines. Accenture's current clients include 91 of the Fortune Global 100 and more than three-quarters of the Fortune Global 500.",
		"companyEstablishment": "1989",
		"companyWebsite": "https://www.accenture.com/",
		"companyAddDate": "2024-01-01T03:48:06.000Z",
		"companyAddedBy": 5,
		"ImageID": "1Gjc-4L98OWAMi67ZxkVZQFJuvasj1SMf",
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 6,
		"companyName": "Accolite Digital ",
		"companyClass": 2,
		"companyDescription": "Accolite Digital is a leading provider of cloud and digital product engineering services across the banking and financial services, technology, healthcare, communications and media, and logistics industries. It is an innovative, best-in-class digital transformation services provider, successfully delivering design-driven complex digital transformation initiatives to Fortune 500 clients. By being led and product focussed, They are able to drive compelling business outcomes which when applied to other organizations, encourages cross-team collaboration to drive transformation digital experiences no matter your team or industry.",
		"companyEstablishment": "2007",
		"companyWebsite": "https://www.accolite.com",
		"companyAddDate": "2022-12-18T23:37:53.000Z",
		"companyAddedBy": 5,
		"ImageID": "15RMfChh7pKwFOU0pWk-1tnRBwnJsCFVQ",
		"classID": 2,
		"className": "Core",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 7,
		"companyName": "Algoscale",
		"companyClass": 4,
		"companyDescription": "Algoscale Technologies Inc. is a boutique Data Science and Big Data Analytics firm incorporated in the US with a development center in Noida, India. Applying analytical tools, techniques, and technology, we help organizations gain valuable insights that accelerate business decision-making and increase profitability.",
		"companyEstablishment": "2014",
		"companyWebsite": "https://algoscale.com/",
		"companyAddDate": "2022-12-18T23:41:06.000Z",
		"companyAddedBy": 5,
		"ImageID": "1Ik49Ws4y_HZchJstAyfnHTJu6DptnOBk",
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 8,
		"companyName": "AMAZON",
		"companyClass": 3,
		"companyDescription": "Amazon is an American multinational technology company that focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence. It is one of the Big Five companies in the U.S. information technology industry. The company has been referred to as \"one of the most influential economic and cultural forces in the world\", as well as the world's most valuable brand. Amazon is known for its disruption of well-established industries through technological innovation and mass scale. It is the world's largest online marketplace, AI assistant provider, live-streaming platform, and cloud computing platform as measured by revenue and market capitalization. Amazon is the largest Internet company by revenue in the world.",
		"companyEstablishment": "1994",
		"companyWebsite": "https://www.amazon.com/",
		"companyAddDate": "2022-12-18T23:41:44.000Z",
		"companyAddedBy": 5,
		"ImageID": "11IP1OMKKRGzvmCCUUobouvwhBQE_Eo0m",
		"classID": 3,
		"className": "Elite",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 9,
		"companyName": "Capgemini",
		"companyClass": 1,
		"companyDescription": "Capgemini was founded by Serge Kampf as an enterprise management and data processing company. Capgemini SE is a French multinational corporation that provides consulting, technology, professional, and outsourcing services. It is headquartered in Paris, France. Capgemini has over 270,000 employees in over 50 countries, of whom nearly 120,000 are in India.",
		"companyEstablishment": "1 October 1967",
		"companyWebsite": "www.capgemini.com",
		"companyAddDate": "2022-12-18T23:42:35.000Z",
		"companyAddedBy": 5,
		"ImageID": "1Uagy3wlaV0IBXmp0cgPsjvNJ6FbmA3Y1",
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 10,
		"companyName": "Consultadd Inc.",
		"companyClass": 3,
		"companyDescription": "Consultadd is a more than 10 years old company in IT consulting with 400+ employees globally. In India, we have an office in Pune with 200+ employees with around 40 people in the engineering team.",
		"companyEstablishment": "2011",
		"companyWebsite": "https://consultadd.com/",
		"companyAddDate": "2022-12-18T23:43:39.000Z",
		"companyAddedBy": 5,
		"ImageID": "1DUHaXJMca1Oo4Z0AdblSbdb2iwkhXccQ",
		"classID": 3,
		"className": "Elite",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 11,
		"companyName": "CONSULTADD",
		"companyClass": 4,
		"companyDescription": "ConsultAdd Inc. is a leading provider of Information Technology consulting and business process services. It offers strategic insights, technological expertise, and industry experience. ConsultAdd is one of the fastest growing IT consulting companies specializing in finance, banking, insurance, healthcare, retail, e-commerce domains and enterprise web development, data warehouse, business intelligence, big data in technologies.\r\nWith over 150 professionals working on information technology projects across the united states, ConsultAdd is headquartered in TX and has a presence in Virginia, Pennsylvania, New York. ConsultAdd's offshore center is based in India at Pune.",
		"companyEstablishment": "2011",
		"companyWebsite": "https://www.consultadd.com/",
		"companyAddDate": "2022-02-08T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 12,
		"companyName": "DXC Technology",
		"companyClass": 1,
		"companyDescription": "DXC Technology (NYSE: DXC)?helps global companies run their mission critical systems and operations while modernizing IT, optimizing data architectures, and ensuring security and scalability across public, private and hybrid clouds. With decades of driving innovation, the world’s largest companies trust DXC to deploy the Enterprise Technology Stack to deliver new levels of performance, competitiveness and customer experiences.",
		"companyEstablishment": "2017",
		"companyWebsite": "https://dxc.com/no/en",
		"companyAddDate": "2022-12-18T23:44:15.000Z",
		"companyAddedBy": 5,
		"ImageID": "1aYYGJn3-qj6wYv1y4GIeCgY5AkTSZd7r",
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 13,
		"companyName": "GalaxE Solution",
		"companyClass": 4,
		"companyDescription": "GalaxE Solution, headquartered in Somerset, New Jersey, and established in 1990, is an IT service management company. They offer a variety of solutions, including application development, business consulting, infrastructure and security, digital strategy, and transformation services.",
		"companyEstablishment": "1990",
		"companyWebsite": "https://galaxe.com/",
		"companyAddDate": "2022-12-18T23:45:00.000Z",
		"companyAddedBy": 5,
		"ImageID": "1wBbsvIqGOOPxAocHP1y19VFOkQqM6dtB",
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 14,
		"companyName": "WIPRO",
		"companyClass": 1,
		"companyDescription": "Wipro Limited is an Indian multinational corporation that provides information technology, consulting and business process services. The Fortune India 500 ranks it the 29th largest Indian company by total revenue. It is also ranked the 9th largest employer in India with over 221,000 employees. It is headquartered in Bangalore, Karnataka, India.",
		"companyEstablishment": "1945",
		"companyWebsite": "https://www.wipro.com/",
		"companyAddDate": "2022-12-18T23:45:52.000Z",
		"companyAddedBy": 7,
		"ImageID": "1wVpS8Pqe8DWnmXEsgfzv3RMNhyGLwnSc",
		"classID": 1,
		"className": "Major",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 15,
		"companyName": "Saas lab",
		"companyClass": 4,
		"companyDescription": "SaaS Labs Inc is a Noida-based software company where we build innovative B2B products for small & medium-sized businesses around the world. Our products like JustCall, CallRoot & Helpwise serve over 100,000 businesses in 40+ countries",
		"companyEstablishment": "2014",
		"companyWebsite": "http://saaslabs.co",
		"companyAddDate": "2022-12-18T23:47:10.000Z",
		"companyAddedBy": 7,
		"ImageID": "1b4RYgQtXtnTH6t-INYSOiYGRmN-YTow-",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 16,
		"companyName": "UNTHINKABLE",
		"companyClass": 4,
		"companyDescription": "Unthinkable, we help our customers to disrupt faster by decreasing time-to-market via reducing the time gap between an idea and working software. Combining our experience of building 100+ software solutions and developing products using decoupled software components to reduce redundant code, we are in a unique position to make this an unconventional approach to software development. Unthinkable is the software services brand of Applane Solutions LLP, and a group company of Daffodil Software.",
		"companyEstablishment": "1999",
		"companyWebsite": "www.unthinkable.co",
		"companyAddDate": "2022-12-18T23:48:11.000Z",
		"companyAddedBy": 7,
		"ImageID": "1DUeEyf8KKq8DmkeWfxIzLYvsrXdRj7wQ",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 17,
		"companyName": "Play Simple",
		"companyClass": 3,
		"companyDescription": "Play Simple is one of India’s most exciting, fast-growing and largest mobile gaming companies. Founded in 2014, and backed by Elevation Capital & Chirata e Ventures. Its vision is to create simple, impactful casual game experiences at a massive scale.\r\nIt has built a worldwide network of chart-topping games, and powerful tech & analytics infrastructure to turbo-charge their growth. Its product portfolio consists of fever green hits like Daily Themed Crossword, Word Trip, Word Jam, Word Wars, Word Trek and Solitaire.",
		"companyEstablishment": "2014",
		"companyWebsite": "http://www.playsimple.in",
		"companyAddDate": "2022-12-18T23:48:42.000Z",
		"companyAddedBy": 7,
		"ImageID": "16wO7tPfhzGchN1k_lJHBIuJKPyd-5BVK",
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 18,
		"companyName": "Pep-Coding",
		"companyClass": 3,
		"companyDescription": "Pep-coding, founded in 2017 with the vision to bring in \"The Great Indian Coding Renaissance\". We specialize in teaching in Data Structure, Algorithms and Web Development and getting the best results. Pep-coding stands out as the best place for anyone, be it a beginner or a pro if you are actually in pursuit of achieving excellence in programming.",
		"companyEstablishment": "2017",
		"companyWebsite": "https://www.pepcoding.com/",
		"companyAddDate": "2022-12-18T23:49:25.000Z",
		"companyAddedBy": 7,
		"ImageID": "1vIX8vQc1ru4V7XnF6pidjq96-xGeeaLm",
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 19,
		"companyName": "OPTUM",
		"companyClass": 4,
		"companyDescription": "Optum is a health information technology and services firm that is part of United Health Group. It provides technological, operational and consulting solutions and services to individuals, healthcare organizations, pharmaceutical companies as well as the federal and state governments. Optum has been operating in India since 2006 and has teams supporting health care operations, product development, automation, analytics and data solutions.",
		"companyEstablishment": "2006",
		"companyWebsite": "https://www.optum.in/",
		"companyAddDate": "2022-12-18T23:50:14.000Z",
		"companyAddedBy": 7,
		"ImageID": "11JaWIWk_IhehMQsgIUmrW5AaBJEwBpJ5",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 20,
		"companyName": "Lowe's",
		"companyClass": 3,
		"companyDescription": "Lowe’s Company is a FORTUNE 50 home improvement company serving approximately 20 million customers a week in the United States and Canada. With the fiscal year 2020 sales of close to $90 billion, Lowe’s and its related businesses operate or service more than 2,200 home improvement and hardware stores and employ over 300,000 associates. Based in Mooresville, N.C., Lowe’s supports the communities it serves through programs focused on creating safe, affordable housing and helping to develop the next generation of skilled trade experts.",
		"companyEstablishment": "1946",
		"companyWebsite": "https://www.lowes.com/",
		"companyAddDate": "2022-12-18T23:50:48.000Z",
		"companyAddedBy": 7,
		"ImageID": "1QG70KpJUB06mtxRGoC51MHvDcpzmLs2g",
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 21,
		"companyName": "Rapi-Pay",
		"companyClass": 3,
		"companyDescription": "Rapi-Pay is building the largest network of \"Rapi-Pay Saathis\" - competent and equipped with technology and connectivity to provide retail financial services via a one-stop payments solution platform to its end customers, in a manner that is simple and secure. It brings banking services to your trusted nearby shop helping customers manage their money and keeps their lives moving.",
		"companyEstablishment": "2009",
		"companyWebsite": "https://www.rapipay.com/web/#/",
		"companyAddDate": "2022-12-18T23:51:19.000Z",
		"companyAddedBy": 7,
		"ImageID": "11JViWxcrAlSBK4k0Dutj0D3IZ1SlMBJJ",
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 22,
		"companyName": "McKinley & Rice",
		"companyClass": 4,
		"companyDescription": "McKinley & Rice is a multinational HR management startup operating in South Korea, the U.S., and\r\nIndia. What is an HR management company? It means we’re experts in management, and we’re experts in people. (We’re also experts in recruitment, and we engineer and operate a recruitment platform that\r\ncompetes against LinkedIn, Indeed, and Naukri.) We know why so many international companies are\r\nafraid of entering India. We also know why so many talented employees are unhappy working for\r\noutsourcing consultancies like Infosys or TCS.\r\nWe operate the overseas divisions for various multinational companies. International companies come to\r\nus for top talent, and top talent comes to us for interesting, meaningful jobs. In India, we're located in Noida and Pune with a total of around 70+ innovative people working for various MNCs, and as a startup, we’ve been growing explosively at 300% year after year.",
		"companyEstablishment": "2018",
		"companyWebsite": "https://www.mckinleyrice.com/",
		"companyAddDate": "2022-02-25T07:41:53.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 23,
		"companyName": "Josh Technology Group",
		"companyClass": 3,
		"companyDescription": "JTG Software has been providing advanced and customized technological solutions for its clients for over a decade with a focus on overcoming business challenges, empowering companies, and unlocking new opportunities for business growth and increased revenue. With a rapidly growing client base across countries like the United States, Ukraine, Russia, Costa Rica, China, Bangladesh, and Brazil (to name a few), JTG strives to make a mark in the technology industry by leveraging the latest in technology to solve problems and create a paradigm shift in the business landscape globally. Catering to diverse domains including automotive, manufacturing, healthcare, financial services, and telecommunications, our platforms, services, tools, and methodology are helping organizations become future-ready.",
		"companyEstablishment": "2009",
		"companyWebsite": "https://www.joshtechnologygroup.com/",
		"companyAddDate": "2022-12-18T23:53:00.000Z",
		"companyAddedBy": 7,
		"ImageID": "17Mtmt3FRSVPUpwMHIQQtFmSkIgt2fRvp",
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 24,
		"companyName": "ION Group",
		"companyClass": 3,
		"companyDescription": "ION Group is a privately held, global financial software and data firm that provides technology for trading and execution, risk management and position calculation, connectivity to exchanges and markets, and technology for middle and back-office processes. The firm offers its software across most asset classes and works with trading and brokerage firms, multinational corporations, governments, and central banks.",
		"companyEstablishment": "1999",
		"companyWebsite": "https://iongroup.com/",
		"companyAddDate": "2022-12-18T23:53:33.000Z",
		"companyAddedBy": 7,
		"ImageID": "1nYd3t9UHy7jXWD3JECv722mSGwTMuBq1",
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 25,
		"companyName": "Appinventiv technology",
		"companyClass": 4,
		"companyDescription": "Appinventiv is a leading global App Development Company that's Empowering Disruptive Startups & Fortune 500 companies in bridging the gap between Ideas and Reality through innovative Mobile solutions. We have a talented team of 500+ Mobility experts, who have successfully Designed, Developed & Delivered more than 900+ Mobile Apps globally in just 5 years.\r\n\r\nBreaking all growth records, we believe our Work Culture is what drives us and made all this possible to have emerged as one of the most trusted & fastest growing company in the Industry.",
		"companyEstablishment": "08 June 2016",
		"companyWebsite": "https://appinventiv.com/",
		"companyAddDate": "2022-12-18T23:54:10.000Z",
		"companyAddedBy": 5,
		"ImageID": "1VcgM7Anlsw41Ti9PLPRZE11o3xmtUwvX",
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 26,
		"companyName": "Infosys ",
		"companyClass": 1,
		"companyDescription": "Infosys provides software development, maintenance, and independent validation services to companies in finance, insurance,  manufacturing, and other domains. Infosys Limited is an Indian multinational information technology company that provides business consulting, information technology, and outsourcing services. The company was founded in Pune and is headquartered in Bangalore .One of its known products is Finacle which is a  universal banking solution with various modules for retail and corporate banking.",
		"companyEstablishment": "1981",
		"companyWebsite": "www.infosys.com",
		"companyAddDate": "2022-02-13T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 27,
		"companyName": "Info Edge",
		"companyClass": 4,
		"companyDescription": "Info Edge has an in-depth understanding of the Indian consumer internet domain. With years of experience in the domain, strong cash flow generation, and a diversified business portfolio, it is one of the very few profitable pure play internet companies in the country.",
		"companyEstablishment": "1 May 1995",
		"companyWebsite": "http://www.infoedge.in",
		"companyAddDate": "2022-12-18T23:55:35.000Z",
		"companyAddedBy": 7,
		"ImageID": "1JGL779Pn829VQl2T7cKdXKZnphtg0SAo",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 28,
		"companyName": "HEXAWARE",
		"companyClass": 4,
		"companyDescription": "Hexaware is a fast-growing automation-led next-generation service provider delivering excellence in IT, BPO, and consulting services. They are driven by a combination of robust strategies, passionate teams, and a global culture rooted in innovation and automation. \r\n\r\nHexaware’s Digital offerings have helped clients achieve operational excellence and customer delight. Their focus lies on taking a leadership position in helping clients attain customer intimacy as their competitive advantage.",
		"companyEstablishment": "1990",
		"companyWebsite": "https://hexaware.com/",
		"companyAddDate": "2022-12-18T23:56:14.000Z",
		"companyAddedBy": 7,
		"ImageID": "1V1QGuzFKspJ2r9lqMdB9rhbElBzxTVvH",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 29,
		"companyName": "Hevo data",
		"companyClass": 3,
		"companyDescription": "Hevo is a no-code data pipeline platform that helps new-age businesses integrate their data from multiple sources to any data warehouse in almost real-time. The platform supports 100+ ready-to-use integrations across Databases, SaaS Applications, Cloud Storage, SDKs, and Streaming Services.",
		"companyEstablishment": "2016",
		"companyWebsite": "https://hevodata.com/",
		"companyAddDate": "2022-02-13T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 30,
		"companyName": "Cloud Analogy",
		"companyClass": 4,
		"companyDescription": "Cloud Analogy is a top-rated Salesforce development and consulting company of 210+ certified professionals and consultants. They have deep domain knowledge and skilful expertise in providing the best-in-class Salesforce implementation, consulting, and migration services for your businesses, primarily Global Fortune 500 companies and some of the world’s largest CRM-powered companies.",
		"companyEstablishment": "2015",
		"companyWebsite": "https://www.cloudanalogy.com/",
		"companyAddDate": "2022-12-18T23:57:54.000Z",
		"companyAddedBy": 7,
		"ImageID": "1V1QGuzFKspJ2r9lqMdB9rhbElBzxTVvH",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 31,
		"companyName": "HEALTHKART",
		"companyClass": 4,
		"companyDescription": "HealthKart is India’s leading nutrition and supplement platform that offers a comprehensive range of products, engagement tools, and expert assistance for all your wellness and fitness needs.",
		"companyEstablishment": "2011",
		"companyWebsite": "https://www.healthkart.com/",
		"companyAddDate": "2022-12-18T23:59:02.000Z",
		"companyAddedBy": 7,
		"ImageID": "1ObW8x9-EwHiXiGM47EWAdTU_QCYNxMYR",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 32,
		"companyName": "InvestWell",
		"companyClass": 4,
		"companyDescription": "InvestWell builds software and mobile applications for Mutual Fund Distributors, Independent Financial Advisors, and investors for making and tracking investments in various securities.  It was opened in 2000 and since then has built numerous software applications for financial advisors. It is based in New Delhi and is serving clients in over 70 cities in India. It also offers services for customized development and integration services.   We develop and maintain a large number of financial advisor web portals, and provide quality web content services for such portals.",
		"companyEstablishment": "2000",
		"companyWebsite": "https://www.investwellonline.com/",
		"companyAddDate": "2022-12-18T23:59:49.000Z",
		"companyAddedBy": 7,
		"ImageID": "1SI920cEDG16CicEqs3jbG8LtNxlylYDo",
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 33,
		"companyName": "upGrad",
		"companyClass": 1,
		"companyDescription": "upGrad is an Indian online higher education company, founded in 2015. The company is the official education partner for the Government of India - Startup India program. The EdTech company offers online programs to working professionals, college students, and corporates in the fields of IT,  data science, management and technology.",
		"companyEstablishment": "2015",
		"companyWebsite": "https://www.upgrad.com/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 34,
		"companyName": "Kuliza",
		"companyClass": 4,
		"companyDescription": "Kuliza is a leading provider of digital transformation and operational intelligence solutions for financial enterprises. Since 2006, Kuliza has executed more than 120 digital transformation projects for global startups and industry-leading global enterprises. Lend. In is Kuliza’s flagship lending product, The low code lending suite for banks and lending institutions to increase the overall efficiencies while decreasing the cost and go-to-market time for customers. The idea to scale, evolve, and continuously improve loan processing by leveraging the customer-centric design and new-age technologies is brought live using Lend.",
		"companyEstablishment": "2006",
		"companyWebsite": "http://www.kuliza.com",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 35,
		"companyName": "BYJU’s",
		"companyClass": 1,
		"companyDescription": "BYJU'S is an Indian multinational educational technology company, headquartered in Bangalore and  established in 2011. As of June 2021, BYJU'S is worth US $18 billion, making it one of the world's most valuable educational technology companies in the world.",
		"companyEstablishment": "2011",
		"companyWebsite": "https://byjus.com/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 36,
		"companyName": "Chegg",
		"companyClass": 1,
		"companyDescription": "Chegg Inc. is an American education technology company based in Santa Clara, California. It provides digital and physical textbook rentals, textbook solutions, online tutoring, and other student services. The company was launched in 2005 and began trading publicly on the New York Stock Exchange in November 2013.",
		"companyEstablishment": "2005",
		"companyWebsite": "https://www.chegg.com/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 37,
		"companyName": "HINDUSTAN UNILEVER",
		"companyClass": 1,
		"companyDescription": "Hindustan Unilever Limited is a consumer goods company, headquartered in Mumbai, India. It is a subsidiary of Unilever, a British company. Its products include foods, beverages, cleaning agents, personal care products, water purifiers, and other fast-moving consumer goods.",
		"companyEstablishment": "1933",
		"companyWebsite": "https://www.hul.co.in/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 38,
		"companyName": "UKG(Kronos)",
		"companyClass": 1,
		"companyDescription": "Ultimate Kronos Group is an American multinational technology company with dual headquarters in Lowell, Massachusetts, and Weston, Florida. It provides workforce management and human resource management services.",
		"companyEstablishment": "1977",
		"companyWebsite": "https://www.ukg.com/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 39,
		"companyName": "KPIT",
		"companyClass": 1,
		"companyDescription": "KPIT Technologies Limited is an Indian multinational corporation,headquartered in Pune, Maharashtra, India. Popularly known as KPIT, it provides software to automotive companies. KPIT has development centers in Europe, USA, Japan, China, Thailand and India.",
		"companyEstablishment": "1990",
		"companyWebsite": "https://www.kpit.com/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 40,
		"companyName": "COGNIZANT",
		"companyClass": 1,
		"companyDescription": "Cognizant is an American multinational technology company that provides business consulting, information technology, and outsourcing services. The major employee base of the company lies in Chennai, Tamil Nadu. There are other branch offices of Cognizant India in various cities across the country including Kolkata, Bangalore, Hyderabad, Mumbai, Pune, Coimbatore and Cochin.",
		"companyEstablishment": "1994",
		"companyWebsite": "https://www.cognizant.com/in/en",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 41,
		"companyName": "Country Delight ",
		"companyClass": 4,
		"companyDescription": "Country Delight delivers farm-fresh cow and buffalo milk to your doorstep within a few hours of milking.",
		"companyEstablishment": "2015",
		"companyWebsite": "https://countrydelight.in/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 42,
		"companyName": "DishTV",
		"companyClass": 4,
		"companyDescription": "DishTV India is an Indian direct broadcast satellite service provider in India with Yes Bank as the biggest stake owner. DishTV was launched by the Zee Group on 2 October 2003. It ranked # 437 and # 5 on the list of media companies in the Fortune India 500 roster of India's largest corporations in 2011.",
		"companyEstablishment": "2003",
		"companyWebsite": "https://www.dishtv.in/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 43,
		"companyName": "IFFCO-TOKIO",
		"companyClass": 4,
		"companyDescription": "IFFCO-Tokio General Insurance Company Limited was incorporated in 2000, as a joint venture between the Indian Farmers Fertiliser Cooperative Limited (IFFCO), which is the world’s largest fertilizer manufacturer, and Tokio Marine Group, which is one of the largest insurance groups in Japan. IFFCO holds 51 percent of the company and the remaining 49 percent is held by Tokio Marine Group.",
		"companyEstablishment": "2000",
		"companyWebsite": "https://www.iffcotokio.co.in/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 44,
		"companyName": "Juspay Technology",
		"companyClass": 3,
		"companyDescription": "JUSPAY is a payments exchange connecting merchants, payment providers, and banks. With a deep focus on delivering seamless payments UX at scale, we are trusted partners for all major internet companies in India. After surpassing 200M SDK installs, building systems handling the highest payments traffic in India of 2000 transactions per second, we are now making the next stride to power end-to-end payments for India.",
		"companyEstablishment": "2012",
		"companyWebsite": "https://juspay.in/",
		"companyAddDate": "2022-02-17T04:52:06.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 45,
		"companyName": "Morgan Stanley",
		"companyClass": 3,
		"companyDescription": "Morgan Stanley is an American multinational investment bank and financial services company headquartered at 1585 Broadway in the Morgan Stanley Building, Midtown Manhattan, New York City. With offices in more than 42 countries and more than 60,000 employees, the firm's clients include corporations, governments, institutions, and individuals. Morgan Stanley ranked No. 67 in the 2018 Fortune 500 list of the largest United States corporations by total revenue.",
		"companyEstablishment": "1935",
		"companyWebsite": "https://www.morganstanley.com/",
		"companyAddDate": "2022-02-17T04:40:43.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 46,
		"companyName": "Samsung R&D",
		"companyClass": 4,
		"companyDescription": "Samsung R&D Institute India-Noida (SRI-Noida) is a dedicated mobile software R&D centre of Samsung India Electronics Private Limited. SRI-Noida’s young and talented workforce aims to deliver quality and advanced products with passion and speed. The environment fosters collaboration; teamwork and provides a platform for quick decisions and implementations. Year on year, new achievements added feathers to our cap. In just a decade of its journey, SRI-Noida expanded from 40 people to over 2300 people, shifted to a state of the art campus dedicated to mobile R&D, and boasts of over 400 patents filed globally, that serves as a testament to our culture of innovation.",
		"companyEstablishment": "1996",
		"companyWebsite": "https://research.samsung.com/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 47,
		"companyName": "Flipkart",
		"companyClass": 3,
		"companyDescription": "Flipkart is an Indian e-commerce company, headquartered in Bangalore, Karnataka, India, and incorporated in Singapore as a private limited company. The company initially focused on online book sales before expanding into other product categories such as consumer electronics, fashion, home essentials, groceries, and lifestyle products.\r\nThe service competes primarily with Amazon's Indian subsidiary and domestic rival Snapdeal. As of March 2017, Flipkart held a 39.5% market share of India's e-commerce industry.",
		"companyEstablishment": "2007",
		"companyWebsite": "https://www.flipkartcareers.com/",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 48,
		"companyName": "Goldman Sachs",
		"companyClass": 3,
		"companyDescription": "The Goldman Sachs Group, Inc. is a leading global financial institution that delivers a broad range of financial services across investment banking, securities, investment management, and consumer banking to a large and diversified client base that includes corporations, financial institutions, governments, and individuals.\r\nFounded in 1869, the firm is headquartered in New York and maintains offices in all major financial centres around the world.",
		"companyEstablishment": "1869",
		"companyWebsite": "https://www.goldmansachs.com",
		"companyAddDate": "2022-02-16T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 49,
		"companyName": "Gemini Solutions",
		"companyClass": 4,
		"companyDescription": "Gemini Solutions is a global IT firm, a leading offshore outsourcing company with a specialized focus on financial services. Gemini offers several management services and can combine our range of services to suit a diverse range of needs. Having a well-equipped automated corporate office in Gurgaon and a nationwide network of associate offices.",
		"companyEstablishment": "2012",
		"companyWebsite": "https://www.geminisolutions.com/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 50,
		"companyName": "INFOGAIN",
		"companyClass": 4,
		"companyDescription": "Infogain is a human-centric digital platform and software engineering company based in Silicon Valley. We design business outcomes for Fortune 500 companies and digital natives in the areas of healthcare, insurance, travel, telecom, and retail & CPG industries using technologies such as cloud, microservices, automation, IoT, and artificial intelligence. We are accelerating experience-based transformation in delivering digital platforms. Infogain is also a Microsoft Gold Partner and Azure Expert Managed Services Provider (MSP).",
		"companyEstablishment": "1990",
		"companyWebsite": "https://www.infogain.com/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 51,
		"companyName": "InnoBit Systems",
		"companyClass": 4,
		"companyDescription": "InnoBit Systems Private Limited is an unlisted private company incorporated on 18 December, 2018. It is classified as a private limited company and is located in Gautam Buddha Nagar, Uttar Pradesh. It’s authorized share capital is INR 1.00 lac and the total paid-up capital is INR 1.00 lacs.\r\nIt brings product thinking from our years of experience of having delivered products in various domains such as Internet of Things (IoT), cloud computing, artificial intelligence, machine learning, collaboration, and multimedia",
		"companyEstablishment": "2018",
		"companyWebsite": "https://innobitsystems.com/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 52,
		"companyName": "Internet Research Bureau",
		"companyClass": 4,
		"companyDescription": "Internet Research Bureau is a global survey company, specializing in quantitative online research and respondent engagement.The headquarter is in New Delhi with regional headquarters in the US and in the UK, Internet Research Bureau serves clients in over 40 countries worldwide. The core services include engaging with niche consumer panels globally to gain market insights and designing, programming, and conducting client surveys. The company relies on organically acquired and relevant data sources.",
		"companyEstablishment": "2011",
		"companyWebsite": "https://www.irbureau.com/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 53,
		"companyName": "POSist",
		"companyClass": 4,
		"companyDescription": "This company was launched in 2012, POSist is a leading cloud-based restaurant technology platform suited for restaurants of all sizes. POSist offers scalable, reliable, and easy-to-use point-of-sale technology, enabling businesses to automate operations, integrate with aggregators, delight guests, and grow their revenue. POSist is trusted by over 10,000+ restaurants in 35 countries worldwide.",
		"companyEstablishment": "2012",
		"companyWebsite": "https://www.posist.com/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 54,
		"companyName": "Artech Infosystem",
		"companyClass": 1,
		"companyDescription": "Artech is a women-owned business enterprise (WBE) committed to maximizing global workforce solutions on behalf of its clients. Artech's deep heritage, proven expertise, and insightful market intelligence have secured long-term partnerships with Fortune 500 and government clients seeking world-class professional resources. Artech provides the most innovative, efficient, and cost-effective workforce solutions in today's marketplace. Artech leverages its mature, quality-certified processes to provide a variety of standard and customized solutions and programs to help clients optimize their supply chain and increase time to market of their workforce requirements, hence, accelerating project progress",
		"companyEstablishment": "1992",
		"companyWebsite": "https://www.artechinfo.in/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 55,
		"companyName": "BITCS",
		"companyClass": 1,
		"companyDescription": "The BITCS community includes experts from around the globe with expertise in a wide variety of software development languages and technologies. We work around the best technology to provide you with quality products, enhance your business on a global level and come up with all the market-leading solutions for you.",
		"companyEstablishment": "2017",
		"companyWebsite": "https://bitcs.in/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 56,
		"companyName": "MothersonSumi",
		"companyClass": 1,
		"companyDescription": "Motherson Sumi Systems Limited is an Indian manufacturer and global supplier of automotive components. Established in 1986 and part of the Motherson Group, Motherson Sumi Systems is a joint venture between Samvardhana Motherson International Ltd of India and Sumitomo Wiring Systems Ltd. of Japan.",
		"companyEstablishment": "1986",
		"companyWebsite": "https://www.motherson.com/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 57,
		"companyName": "Newgen",
		"companyClass": 1,
		"companyDescription": "Newgen is the leading provider of a unified digital transformation platform with native process automation, content services, and communication management capabilities. Globally, successful enterprises rely on Newgen’s industry-recognized low code application platform to develop and deploy complex, content-driven, and customer-engaging business applications on the cloud. From onboarding to service requests, lending to underwriting, and for many more use cases across industries. Newgen unlocks simplicity with speed and agility.",
		"companyEstablishment": "1992",
		"companyWebsite": "https://newgensoft.com/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 58,
		"companyName": "Sunstone Eduversity",
		"companyClass": 1,
		"companyDescription": "Sunstone Eduversity is India’s first higher education provider to take complete accountability of a students’ career through their pay after placement MBA, PGDM, BBA, Online MBA & MCA programs. It offers UGC/AICTE approved programs in partnership with 23+ leading campuses across the country. Sunstone aims to make higher education more accountable, pragmatic and tailored to the demands of the corporate world. Through this, Sunstone enhances the skill set of students in addition to making them, capable professionals.",
		"companyEstablishment": "2011",
		"companyWebsite": "https://sunstone.edu.in/",
		"companyAddDate": "2022-02-17T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 59,
		"companyName": "EPAM",
		"companyClass": 4,
		"companyDescription": "EPAM Systems, Inc. is an American company that specializes in product development, digital platform engineering, and digital product design. One of the world's largest manufacturers of custom software and consulting providers. The company's headquarters is located in Newtown, Pennsylvania, and its branches are represented in more than 40 countries.",
		"companyEstablishment": "1983",
		"companyWebsite": "https://www.epam.com/",
		"companyAddDate": "2022-02-18T05:54:05.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 60,
		"companyName": "Lens Corporation USA",
		"companyClass": 3,
		"companyDescription": "A better world with machine vision. Founded in the city of Lansing, MI, in 2016, LENS has grown into a global enterprise. We provide state-of-the-art AI solutions developed in-house with the help of professionals and academicians working around the globe.",
		"companyEstablishment": "2016",
		"companyWebsite": "https://lenscorp.ai/",
		"companyAddDate": "2022-02-18T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 61,
		"companyName": "The Bank of New York Mellon",
		"companyClass": 3,
		"companyDescription": "The Bank of New York Mellon Corporation, commonly known as BNY Mellon, is an American investment banking services holding company headquartered in New York City. BNY Mellon was formed from the merger of The Bank of New York and the Mellon Financial Corporation in 2007. It is the world's largest custodian bank and asset servicing company; it is considered a systemically important bank by the Financial Stability Board. BNY Mellon is incorporated in Delaware.",
		"companyEstablishment": "2007",
		"companyWebsite": "https://www.bnymellon.com/",
		"companyAddDate": "2022-02-18T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 3,
		"className": "Elite",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 62,
		"companyName": "Vinculum Solutions",
		"companyClass": 1,
		"companyDescription": "Vinculum Solutions is the Point of Difference between Selling and Smart selling. If you want to make scaling your business as easy as reading our bio, then this is your one-stop solution to support consistent growth by recognizing and overcoming any real-time retail challenge. We help save time and money for quick digital expansion using 150+ ready integrations of marketplaces, web stores & last-mile fulfilment companies that are built-in to our software.",
		"companyEstablishment": "2007",
		"companyWebsite": "https://www.vinculumgroup.com/",
		"companyAddDate": "2022-02-18T11:30:00.000Z",
		"companyAddedBy": 7,
		"ImageID": null,
		"classID": 1,
		"className": "Major",
		"userID": 7,
		"userName": "Shagun",
		"userEmail": "shagun@stcadmin.com",
		"userPassword": "DVX1hSa28i6mJn3EDCOHog==",
		"userType": "Admin"
	},
	{
		"companyID": 63,
		"companyName": "Sunstone Eduversity",
		"companyClass": 4,
		"companyDescription": "Sunstone aims to make higher education more accountable, pragmatic, and tailored to the demands of the corporate world. Through this, Sunstone enhances the skill set of students in addition to making them capable professionals.",
		"companyEstablishment": "2015",
		"companyWebsite": "https://sunstone.in/",
		"companyAddDate": "2022-02-18T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 64,
		"companyName": "Tech Mahindra",
		"companyClass": 4,
		"companyDescription": "Tech Mahindra is an Indian multinational technology company that provides Information Technology (IT) and Business Process Outsourcing (BPO) services. Tech Mahindra is one of the fastest-growing brands and amongst the top 15 IT service providers globally. Tech Mahindra has consistently emerged as a leader in sustainability and is recognized amongst the 2021 global 100 most sustainable corporations in the world by Corporate Knights.",
		"companyEstablishment": "1986",
		"companyWebsite": "https://www.techmahindra.com/",
		"companyAddDate": "2022-02-18T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 65,
		"companyName": "Career Labs",
		"companyClass": 4,
		"companyDescription": "Since their inception in 2019, CareerLabs has successfully garnered the trust of thousands of college students & young working professionals, becoming the go-to place for all their career needs. Envisioning to empower 1 million undergraduate craft the careers of their choosing, they offer a variety of aptly matched and mentor-driven preparatory programs for national & international entrance exams and admissions consulting services for graduate & business schools, both abroad and in India.",
		"companyEstablishment": "2019",
		"companyWebsite": "https://thecareerlabs.com/",
		"companyAddDate": "2022-02-18T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 66,
		"companyName": "Cisco",
		"companyClass": 3,
		"companyDescription": "Cisco facilitates to capture the opportunities of tomorrow by proving that amazing things can happen when you connect the unconnected. An integral part of our DNA is creating long-lasting customer partnerships, working together to identify our customers needs and provide solutions that fuel their success. Cisco has preserved this keen focus on solving business challenges since our founding in 1984. Len Bosack and wife Sandy Lerner, both working for Stanford University, wanted to email each other from their respective offices, but technological shortcomings did not allow such communication. A technology had to be invented to deal with disparate local area protocols, and as a result of solving their challenge, the multiprotocol router was born.",
		"companyEstablishment": "1984",
		"companyWebsite": "https://www.cisco.com/",
		"companyAddDate": "2022-02-18T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 3,
		"className": "Elite",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 67,
		"companyName": "Tata Consultancy Services",
		"companyClass": 4,
		"companyDescription": "Tata Consultancy Services (TCS) is an Indian multinational information technology (IT) services and consulting company, headquartered in Mumbai, Maharashtra, India with its largest campus located in Chennai, Tamil Nadu, India. As of February 2021, TCS is the largest IT services company in the world by market capitalization ($200 billion). It is a subsidiary of the Tata Group and operates in 149 locations across 46 countries.",
		"companyEstablishment": "1968",
		"companyWebsite": "https://www.tcs.com/",
		"companyAddDate": "2022-02-18T11:30:00.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 68,
		"companyName": "HSO India",
		"companyClass": 4,
		"companyDescription": "HSO leverages the full power of Microsoft technology to transform the way we work and improve business performance. They help companies modernize business operations, adopt intelligent automation, deliver real-time performance insights and connect the enterprise – accelerating the impact of digital transformation. Founded in 1987 and recognized as a trusted advisor, HSO is one\r\nof the world’s top business solution and implementation partners, large enough to serve, small enough to care.",
		"companyEstablishment": "1987",
		"companyWebsite": "https://www.hso.com/",
		"companyAddDate": "2022-02-23T11:30:00.000Z",
		"companyAddedBy": 4,
		"ImageID": null,
		"classID": 4,
		"className": "Others",
		"userID": 4,
		"userName": "sid@stcadmin.com",
		"userEmail": "sid@stcadmin.com",
		"userPassword": "KxqPMD1Y1HsYYtk6h/oXWgPtvYbkBQ8S1or0rLzodIs=",
		"userType": "Super Admin"
	},
	{
		"companyID": 70,
		"companyName": "Bhola",
		"companyClass": 3,
		"companyDescription": "it is good company",
		"companyEstablishment": "1999",
		"companyWebsite": "yashvarshney.in",
		"companyAddDate": null,
		"companyAddedBy": 5,
		"ImageID": "undefined",
		"classID": 3,
		"className": "Elite",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 71,
		"companyName": "Bhola",
		"companyClass": 3,
		"companyDescription": "it is good company",
		"companyEstablishment": "1999",
		"companyWebsite": "yashvarshney.in",
		"companyAddDate": null,
		"companyAddedBy": 5,
		"ImageID": "undefined",
		"classID": 3,
		"className": "Elite",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	},
	{
		"companyID": 72,
		"companyName": "Bhola",
		"companyClass": 3,
		"companyDescription": "it is good company",
		"companyEstablishment": "1999",
		"companyWebsite": "yashvarshney.in",
		"companyAddDate": "2024-01-01T04:26:35.000Z",
		"companyAddedBy": 5,
		"ImageID": null,
		"classID": 3,
		"className": "Elite",
		"userID": 5,
		"userName": "Mohika",
		"userEmail": "mohika@stcadmin.com",
		"userPassword": "ADSASlUMIX9i97iJWSz48A==",
		"userType": "Admin"
	}
]